### ISSUE TITLE
CMakeLists.txt for Generating Static Library

### ISSUE THREAD

**Issue by alboainin** [AliAlboainin96/LibAstro#1]
the CMakeLists.txt is configured wrong. The File Structure should be `LibAstro/` which contain all the subdirs and files including the cmakelist, inside `LibAstro/` Theres `LibAstro/src` which contain the source code for the library and a sandbox project for testing.
`LibAstro/src/sandbox/test.cpp' will include the library and `LibAstro/src/libastro/` is the library src. The Issue is that CMakeList.txt need to generate the library and link it to sandbox and compile sandbox

**Comment by ayham-1** [comment]
@AliAlboainin96 #2 done

**Comment by ayham-1** [comment]
@AliAlboainin96 #3 found the missing file.

**Comment by alboainin** [comment]
@realaltffour  it was in the bushes hiding right?

**Comment by ayham-1** [comment]
yees, found it and emptied the glock.

**Comment by alboainin** [comment]
@realaltffour  thats how we work
